### ISSUE TITLE
Birdhouse VST works in Ardour 8.6 on Linux (Pop!_OS 22.04)

### ISSUE THREAD

**Issue by abelzile** [madskjeldgaard/Birdhouse#45]
Birdhouse VST works properly in Ardour 8.6 on Linux (Pop!_OS 22.04). [This thread](https://discourse.ardour.org/t/routing-midi-from-vst-on-audio-track-to-midi-track/103989) helped me set up Ardour to send Birdhouse output to a MIDI instrument. I had to host Birdhouse in a MIDI track, not an Audio track as described in that thread, but otherwise the instructions worked fine.

Building Birdhouse required that several libraries be installed:
`sudo apt install libasound2-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libcurl4-openssl-dev libwebkit2gtk-4.0-dev`

**Comment by madskjeldgaard** [comment]
Amazing to hear. Thanks so much for the feedback <3
