### ISSUE TITLE
Error compiling on Windows with VS 17 2022: cannot convert from 'juce::var' to 'juce::String'	

### ISSUE THREAD

**Issue by giohappy** [madskjeldgaard/Birdhouse#46]
This error is thrown everywhere a juve::var is converted to juce::String, e.g. [here](https://github.com/madskjeldgaard/Birdhouse/blob/main/source/PluginProcessor.cpp#L42-L485).

**Comment by giohappy** [comment]
It can be easily fixed by converting each juce::var to juce::String using the [toString()](https://docs.juce.com/master/classvar.html#ad793c4f69e23c4c40e8d3cd29aa3adba) method.
After doing that I was able to build the plugin,

**Comment by madskjeldgaard** [comment]
Thanks for the issue and the fix. Could you be interested in doing the pull request with these fixes ? 

Beat regards

**Comment by giohappy** [comment]
sure @madskjeldgaard I'll do it as soon as I'm back on it.

FYI I'm taking inspiration from you project and expand it with the following features:

- make it accept any (valid) notes and cc. The idea is to have a sigle path accepting note numbers and cc values as parameters. They will be automatically forwarded, without having to map them, and without a limit of 8 paths
- implement timestamped bundles, to be able to schedule midi messages at a given time in the future. This will also allow implementing external sequencers, which might lack accurate clocks. This is the same idea implemented by Supercollider, Sonic Pi, Tidalcycles, etc.

**Comment by madskjeldgaard** [comment]
> sure @madskjeldgaard I'll do it as soon as I'm back on it.
> 
> FYI I'm taking inspiration from you project and expand it with the following features:
> 
> * make it accept any (valid) notes and cc. The idea is to have a sigle path accepting note numbers and cc values as parameters. They will be automatically forwarded, without having to map them, and without a limit of 8 paths
> * support timestamped OSC bundles, to be able to schedule midi messages at a given time in the future. This will also allow implementing external sequencers, which might lack accurate clocks. This is the same idea implemented by Supercollider, Sonic Pi, Tidalcycles, etc.
> 
> Let's see how far I will get :)

Great ideas! 

I would need a bit more explanation of the first idea to fully understand what you're intending with it.

The second idea with time stamps is a big wish for me too, so if you want to create a PR for that at some point that would be sweet. Thanks for the feedback and help.

**Comment by giohappy** [comment]
>I would need a bit more explanation of the first idea to fully understand what you're intending with it.

Let's focus only on midi notes. I suppose we could have a /midi path which accepts two interger params: the mido note (0-127) and the on/off value (0-1). This way you are not limited to the 8 fixed paths, which means 8 notes max (if you use them all for notes).

Maybe I miss something about you're implementation and this is already supported?

**Comment by giohappy** [comment]
@madskjeldgaard PR done https://github.com/madskjeldgaard/Birdhouse/pull/47

**Comment by madskjeldgaard** [comment]
Thanks a lot @giohappy !
